language: node_js
os: osx
node_js:
  - 14
before_script:
  - npm install @11ty/eleventy -g
script: eleventy
deploy:
  fqdn: blog.beardedfolk.com
  local_dir: _site
  provider: pages
  skip_cleanup: true
  strategy: git
  token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep_history: true
  on:
    branch: master